// Package wpadbus は wpa_supplicant の D-Bus API（fi.w1.wpa_supplicant1）による supplicant.Supplicant の実装。
package wpadbus

import (
	"cmp"
	"context"
	"errors"
	"fmt"
	"log/slog"
	"os"
	"path/filepath"
	"slices"
	"sync"
	"time"

	"github.com/godbus/dbus/v5"

	"github.com/oyaguma3/simwifi/internal/supplicant"
)

// D-Bus の名前。
const (
	BusName         = "fi.w1.wpa_supplicant1"
	RootPath        = dbus.ObjectPath("/fi/w1/wpa_supplicant1")
	IfaceRoot       = "fi.w1.wpa_supplicant1"
	IfaceIface      = "fi.w1.wpa_supplicant1.Interface"
	ErrIfaceUnknown = "fi.w1.wpa_supplicant1.InterfaceUnknown"

	ifaceProperties = "org.freedesktop.DBus.Properties"
	defaultDriver   = "nl80211"
)

// DefaultTimeout は 1 回の D-Bus 呼び出しの待ち時間。
const DefaultTimeout = 10 * time.Second

// ConfigContent は Interface 用設定ファイルの内容（DESIGN §7.3）。
const ConfigContent = "# generated by simwifi; do not edit\nexternal_sim=1\n"

// Client は wpa_supplicant の D-Bus クライアント。
type Client struct {
	conn    *dbus.Conn
	log     *slog.Logger
	timeout time.Duration

	mu         sync.Mutex
	path       dbus.ObjectPath // Attach した Interface
	created    bool
	configPath string
	sigCh      chan *dbus.Signal
	matches    [][]dbus.MatchOption
	stop       chan struct{}
	stopped    chan struct{}
	simCh      chan supplicant.SIMRequest
	eventCh    chan supplicant.Event
}

var _ supplicant.Supplicant = (*Client)(nil)

// New は Client を作る。conn は system bus（テストではプライベートバス）。
func New(conn *dbus.Conn, logger *slog.Logger) *Client {
	if logger == nil {
		logger = slog.New(slog.DiscardHandler)
	}
	return &Client{conn: conn, log: logger.With("component", "supplicant"), timeout: DefaultTimeout}
}

func (c *Client) call(ctx context.Context, p dbus.ObjectPath, method string, args ...any) *dbus.Call {
	ctx, cancel := context.WithTimeout(ctx, c.timeout)
	defer cancel()
	return c.conn.Object(BusName, p).CallWithContext(ctx, method, 0, args...)
}

// Running は wpa_supplicant がバスに居るかを返す（activation は起こさない）。
func (c *Client) Running(ctx context.Context) (bool, error) {
	ctx, cancel := context.WithTimeout(ctx, c.timeout)
	defer cancel()
	var has bool
	err := c.conn.BusObject().CallWithContext(ctx, "org.freedesktop.DBus.NameHasOwner", 0, BusName).Store(&has)
	return has, err
}

// Activatable は wpa_supplicant が D-Bus activation で起動できるかを返す。
func (c *Client) Activatable(ctx context.Context) (bool, error) {
	ctx, cancel := context.WithTimeout(ctx, c.timeout)
	defer cancel()
	var names []string
	if err := c.conn.BusObject().CallWithContext(ctx, "org.freedesktop.DBus.ListActivatableNames", 0).Store(&names); err != nil {
		return false, err
	}
	return slices.Contains(names, BusName), nil
}

// ensureRunning は居なければ D-Bus activation で起動を試みる。
func (c *Client) ensureRunning(ctx context.Context) error {
	if ok, err := c.Running(ctx); err != nil {
		return err
	} else if ok {
		return nil
	}
	c.log.Info("wpa_supplicant is not on D-Bus; trying D-Bus activation")
	ctx, cancel := context.WithTimeout(ctx, 30*time.Second)
	defer cancel()
	var reply uint32
	if err := c.conn.BusObject().CallWithContext(ctx, "org.freedesktop.DBus.StartServiceByName", 0, BusName, uint32(0)).Store(&reply); err != nil {
		return fmt.Errorf("%w: %v", supplicant.ErrNotRunning, err)
	}
	return nil
}

// Capabilities は EAP メソッドなどの能力を返す。
func (c *Client) Capabilities(ctx context.Context) (supplicant.Capabilities, error) {
	var caps supplicant.Capabilities
	if err := c.ensureRunning(ctx); err != nil {
		return caps, err
	}
	var props map[string]dbus.Variant
	if err := c.call(ctx, RootPath, ifaceProperties+".GetAll", IfaceRoot).Store(&props); err != nil {
		return caps, fmt.Errorf("get wpa_supplicant properties: %w", err)
	}
	caps.EAPMethods, _ = props["EapMethods"].Value().([]string)
	caps.Global, _ = props["Capabilities"].Value().([]string)

	c.mu.Lock()
	p := c.path
	c.mu.Unlock()
	if p != "" {
		var v dbus.Variant
		if err := c.call(ctx, p, ifaceProperties+".Get", IfaceIface, "Capabilities").Store(&v); err == nil {
			if m, ok := v.Value().(map[string]dbus.Variant); ok {
				caps.KeyMgmt, _ = m["KeyMgmt"].Value().([]string)
			}
		}
	}
	return caps, nil
}

// Inspect は iface の既存 Interface の情報を返す（status 用。何も変更しない）。
func (c *Client) Inspect(ctx context.Context, iface string) (supplicant.InterfaceInfo, error) {
	var info supplicant.InterfaceInfo
	p, err := c.getInterface(ctx, iface)
	if err != nil || p == "" {
		return info, err
	}
	info.Exists = true
	var props map[string]dbus.Variant
	if err := c.call(ctx, p, ifaceProperties+".GetAll", IfaceIface).Store(&props); err != nil {
		return info, fmt.Errorf("get interface properties: %w", err)
	}
	info.ConfigFile, _ = props["ConfigFile"].Value().(string)
	info.State, _ = props["State"].Value().(string)
	return info, nil
}

// getInterface は iface の Interface のパスを返す。無ければ ""。
func (c *Client) getInterface(ctx context.Context, iface string) (dbus.ObjectPath, error) {
	var p dbus.ObjectPath
	err := c.call(ctx, RootPath, IfaceRoot+".GetInterface", iface).Store(&p)
	if err != nil {
		if dbusErrorName(err) == ErrIfaceUnknown {
			return "", nil
		}
		return "", fmt.Errorf("GetInterface(%s): %w", iface, err)
	}
	return p, nil
}

// dbusErrorName は D-Bus エラーの名前を返す（値とポインタの両方に対応）。
func dbusErrorName(err error) string {
	if de, ok := errors.AsType[dbus.Error](err); ok {
		return de.Name
	}
	if de, ok := errors.AsType[*dbus.Error](err); ok && de != nil {
		return de.Name
	}
	return ""
}

// Attach は Interface を用意し、シグナルの購読を始める（DESIGN §4.1）。
func (c *Client) Attach(ctx context.Context, iface string, opts supplicant.AttachOptions) error {
	if opts.ConfigPath == "" {
		return errors.New("wpadbus: config path is required")
	}
	if err := c.ensureRunning(ctx); err != nil {
		return err
	}
	existing, err := c.getInterface(ctx, iface)
	if err != nil {
		return err
	}
	if existing != "" {
		var v dbus.Variant
		if err := c.call(ctx, existing, ifaceProperties+".Get", IfaceIface, "ConfigFile").Store(&v); err != nil {
			return fmt.Errorf("inspect existing interface: %w", err)
		}
		if cf, _ := v.Value().(string); cf != opts.ConfigPath {
			return fmt.Errorf("%w (%s)", supplicant.ErrInterfaceBusy, iface)
		}
		// 前回の simwifi の残骸（ロックを取れた時点でそのプロセスは生きていない）
		c.log.Warn("removing stale wpa_supplicant interface left by a previous simwifi run", "iface", iface)
		if err := c.call(ctx, RootPath, IfaceRoot+".RemoveInterface", existing).Err; err != nil {
			return fmt.Errorf("remove stale interface: %w", err)
		}
	}

	if err := writeConfig(opts.ConfigPath); err != nil {
		return err
	}
	args := map[string]dbus.Variant{
		"Ifname":     dbus.MakeVariant(iface),
		"Driver":     dbus.MakeVariant(cmp.Or(opts.Driver, defaultDriver)),
		"ConfigFile": dbus.MakeVariant(opts.ConfigPath),
	}
	var p dbus.ObjectPath
	if err := c.call(ctx, RootPath, IfaceRoot+".CreateInterface", args).Store(&p); err != nil {
		_ = os.Remove(opts.ConfigPath)
		return fmt.Errorf("CreateInterface(%s): %w", iface, err)
	}
	c.mu.Lock()
	c.path, c.created, c.configPath = p, true, opts.ConfigPath
	c.mu.Unlock()
	c.log.Info("created wpa_supplicant interface", "iface", iface, "path", string(p))

	if err := c.subscribe(ctx, p); err != nil {
		return err
	}
	return nil
}

func writeConfig(path string) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		return fmt.Errorf("create %s: %w", filepath.Dir(path), err)
	}
	if err := os.WriteFile(path, []byte(ConfigContent), 0o600); err != nil {
		return fmt.Errorf("write wpa_supplicant config: %w", err)
	}
	return os.Chmod(path, 0o600)
}

// subscribe はシグナルの購読を始め、振り分け用の goroutine を起動する。
func (c *Client) subscribe(ctx context.Context, p dbus.ObjectPath) error {
	c.matches = [][]dbus.MatchOption{
		{dbus.WithMatchSender(BusName), dbus.WithMatchObjectPath(p)},
		{dbus.WithMatchSender("org.freedesktop.DBus"), dbus.WithMatchMember("NameOwnerChanged"), dbus.WithMatchArg(0, BusName)},
	}
	for _, m := range c.matches {
		if err := c.conn.AddMatchSignalContext(ctx, m...); err != nil {
			return fmt.Errorf("subscribe to wpa_supplicant signals: %w", err)
		}
	}
	c.sigCh = make(chan *dbus.Signal, 64)
	c.simCh = make(chan supplicant.SIMRequest, 16)
	c.eventCh = make(chan supplicant.Event, 64)
	c.stop = make(chan struct{})
	c.stopped = make(chan struct{})
	c.conn.Signal(c.sigCh)
	go c.dispatch(p)
	return nil
}

// dispatch は D-Bus シグナルを SIM 要求とイベントに振り分ける。
func (c *Client) dispatch(p dbus.ObjectPath) {
	defer close(c.stopped)
	for {
		var s *dbus.Signal
		select {
		case <-c.stop:
			return
		case s = <-c.sigCh:
		}
		if s == nil {
			continue
		}
		if s.Name == "org.freedesktop.DBus.NameOwnerChanged" {
			if len(s.Body) == 3 && s.Body[0] == BusName && s.Body[2] == "" {
				c.sendEvent(supplicant.Event{Kind: supplicant.EventGone})
			}
			continue
		}
		if s.Path != p {
			continue
		}
		switch s.Name {
		case IfaceIface + ".NetworkRequest":
			if len(s.Body) != 3 {
				continue
			}
			np, _ := s.Body[0].(dbus.ObjectPath)
			field, _ := s.Body[1].(string)
			text, _ := s.Body[2].(string)
			if field != "SIM" {
				c.log.Debug("ignoring network request", "field", field)
				continue
			}
			select {
			case c.simCh <- supplicant.SIMRequest{Network: supplicant.NetworkID(np), Text: text}:
			case <-c.stop:
				return
			}
		case IfaceIface + ".EAP":
			if len(s.Body) != 2 {
				continue
			}
			st, _ := s.Body[0].(string)
			param, _ := s.Body[1].(string)
			c.sendEvent(supplicant.Event{Kind: supplicant.EventEAP, EAPStatus: st, EAPParameter: param})
		case ifaceProperties + ".PropertiesChanged":
			if len(s.Body) < 2 || s.Body[0] != IfaceIface {
				continue
			}
			changed, _ := s.Body[1].(map[string]dbus.Variant)
			if v, ok := changed["State"]; ok {
				st, _ := v.Value().(string)
				c.sendEvent(supplicant.Event{Kind: supplicant.EventState, State: st})
			}
			if v, ok := changed["DisconnectReason"]; ok {
				r, _ := v.Value().(int32)
				c.sendEvent(supplicant.Event{Kind: supplicant.EventDisconnectReason, Reason: r})
			}
		}
	}
}

func (c *Client) sendEvent(e supplicant.Event) {
	select {
	case c.eventCh <- e:
	case <-c.stop:
	}
}

func (c *Client) attached() (dbus.ObjectPath, error) {
	c.mu.Lock()
	defer c.mu.Unlock()
	if c.path == "" {
		return "", supplicant.ErrNotAttached
	}
	return c.path, nil
}

// AddNetwork はネットワークを追加する（DESIGN §4.1 の表）。
func (c *Client) AddNetwork(ctx context.Context, cfg supplicant.NetworkConfig) (supplicant.NetworkID, error) {
	p, err := c.attached()
	if err != nil {
		return "", err
	}
	args := map[string]dbus.Variant{
		// SSID はバイト列で渡す（wpa_supplicant が hex にするので引用符や特殊文字を気にしなくてよい）
		"ssid":     dbus.MakeVariant([]byte(cfg.SSID)),
		"key_mgmt": dbus.MakeVariant("WPA-EAP"),
		"eap":      dbus.MakeVariant(cfg.EAP),
		"identity": dbus.MakeVariant(cfg.Identity),
		"phase1":   dbus.MakeVariant("result_ind=1"),
	}
	if cfg.WPA3 {
		args["key_mgmt"] = dbus.MakeVariant("WPA-EAP-SHA256")
		args["ieee80211w"] = dbus.MakeVariant(uint32(2))
	}
	var np dbus.ObjectPath
	if err := c.call(ctx, p, IfaceIface+".AddNetwork", args).Store(&np); err != nil {
		return "", fmt.Errorf("AddNetwork: %w", err)
	}
	return supplicant.NetworkID(np), nil
}

// SelectNetwork はネットワークを選択する（接続が始まる）。
func (c *Client) SelectNetwork(ctx context.Context, id supplicant.NetworkID) error {
	p, err := c.attached()
	if err != nil {
		return err
	}
	if err := c.call(ctx, p, IfaceIface+".SelectNetwork", dbus.ObjectPath(id)).Err; err != nil {
		return fmt.Errorf("SelectNetwork: %w", err)
	}
	return nil
}

// RemoveNetwork はネットワークを削除する。
func (c *Client) RemoveNetwork(ctx context.Context, id supplicant.NetworkID) error {
	p, err := c.attached()
	if err != nil {
		return err
	}
	if err := c.call(ctx, p, IfaceIface+".RemoveNetwork", dbus.ObjectPath(id)).Err; err != nil {
		return fmt.Errorf("RemoveNetwork: %w", err)
	}
	return nil
}

// Disconnect は切断する。
func (c *Client) Disconnect(ctx context.Context) error {
	p, err := c.attached()
	if err != nil {
		return err
	}
	return c.call(ctx, p, IfaceIface+".Disconnect").Err
}

// SIMRequests は SIM 要求のチャネルを返す。
func (c *Client) SIMRequests(context.Context) (<-chan supplicant.SIMRequest, error) {
	if _, err := c.attached(); err != nil {
		return nil, err
	}
	return c.simCh, nil
}

// ReplySIM は NetworkReply(path, "SIM", value) を呼ぶ。
func (c *Client) ReplySIM(ctx context.Context, req supplicant.SIMRequest, resp supplicant.SIMResponse) error {
	p, err := c.attached()
	if err != nil {
		return err
	}
	if err := c.call(ctx, p, IfaceIface+".NetworkReply", dbus.ObjectPath(req.Network), "SIM", string(resp)).Err; err != nil {
		return fmt.Errorf("NetworkReply: %w", err)
	}
	return nil
}

// Events は状態変化のチャネルを返す。
func (c *Client) Events(context.Context) (<-chan supplicant.Event, error) {
	if _, err := c.attached(); err != nil {
		return nil, err
	}
	return c.eventCh, nil
}

// Close は購読をやめ、自分で作った Interface を削除し、設定ファイルを消す。
func (c *Client) Close(ctx context.Context) error {
	c.mu.Lock()
	p, created, cfg := c.path, c.created, c.configPath
	c.path, c.created = "", false
	c.mu.Unlock()
	if c.stop != nil {
		c.conn.RemoveSignal(c.sigCh)
		close(c.stop)
		<-c.stopped
		c.stop = nil
		for _, m := range c.matches {
			_ = c.conn.RemoveMatchSignal(m...)
		}
	}
	var errs []error
	if created && p != "" {
		// wpa_supplicant が居ないときに呼ぶと D-Bus activation で起動してしまうので確認する
		if ok, err := c.Running(ctx); err != nil || !ok {
			c.log.Warn("wpa_supplicant is gone; skipping RemoveInterface")
		} else if err := c.call(ctx, RootPath, IfaceRoot+".RemoveInterface", p).Err; err != nil {
			errs = append(errs, fmt.Errorf("RemoveInterface: %w", err))
		} else {
			c.log.Info("removed wpa_supplicant interface", "path", string(p))
		}
	}
	if cfg != "" {
		if err := os.Remove(cfg); err != nil && !errors.Is(err, os.ErrNotExist) {
			errs = append(errs, err)
		}
	}
	return errors.Join(errs...)
}
